lib/dry/validation/schema.rb
spec/integration/rule_groups_spec.rb

Without this change, a schema with group rule would crash if any of those group’s dependant predicates failed (e.g. if you had a schema with `confirmation(:password)` that you called with either the `password` or `password_confirmation` keys missing or with empty values).
Previously, with a simple schema like this, using the new `confirmation` shortcut:
```ruby
schema = Class.new(Dry::Validation::Schema) {
confirmation(:password)
}.new
```
Calling with missing input values will result in a crash:
```
> schema.call({})
NoMethodError: undefined method `input' for nil:NilClass
from /Users/tim/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/dry-validation-cb895f62ba6c/lib/dry/validation/schema.rb:75:in `block (2 levels) in call'
```
The same thing happens if at least one of the input …

Return errors for a group’s dependant predicates if any have failed

---

lib/dry/validation/error.rb
lib/dry/validation/result.rb
lib/dry/validation/rule.rb
lib/dry/validation/rule/result.rb
lib/dry/validation/schema.rb
lib/dry/validation/schema/result.rb
spec/integration/custom_error_messages_spec.rb
spec/integration/schema_form_spec.rb
spec/integration/schema_spec.rb

This PR breaks API but it makes it cleaner:
* `Schema` always uses injected error compiler which can do whatever
* `Schema#messages` **is gone**
* To get compiled messages you can do `Schema#call(input).messages`
* `Schema#call` returns a schema result object which has access to:
* all validation results (can return successes and failures separately too)
* an error set
* compiled messages using the error compiler provided by the schema which uses the error set to produce different representation of raw errors (and it's lazy)
* potentially coerced params
* `Validation::Result` is now an object gathering all rule results (instances of `Rule::Result`), it provides lower level APIs for working with success and failure results
* `Error::Set` is no longer mutable (yay!) and we simply pass it …

Refactor schema/validation result objects

---

lib/dry/validation/messages/abstract.rb

Requiring 'dry-validation' without any other requires produced an error for me:
$ irb -rdry-validation
/Users/johnbackus/.rvm/gems/ruby-2.2.3/gems/dry-validation-0.3.0/lib/dry/validation/messages/abstract.rb:9:in `<class:Abstract>': undefined method `Pathname' for Dry::Validation::Messages::Abstract:Class (NoMethodError)

Add 'pathname' require to messages abstract

---

lib/dry/validation/error_compiler.rb
lib/dry/validation/result.rb
lib/dry/validation/rule.rb
lib/dry/validation/rule/composite.rb
lib/dry/validation/rule/result.rb
lib/dry/validation/rule_compiler.rb
lib/dry/validation/schema.rb
lib/dry/validation/schema/definition.rb
lib/dry/validation/schema/key.rb
lib/dry/validation/schema/rule.rb
lib/dry/validation/schema/value.rb
spec/integration/schema/generic_rules_spec.rb
spec/integration/schema/nested_spec.rb
spec/spec_helper.rb
spec/unit/rule_compiler_spec.rb
spec/unit/rule_spec.rb
spec/unit/schema/rule_spec.rb
spec/unit/schema/value_spec.rb

This adds two big features:
* Ability to define schemas within a schema for complex logic and to be able to re-use schema easily
* Ability to compose generic rules via `rule` syntax and common logic operators
``` ruby
class CitySchema < Dry::Validation::Schema
key(:name, &:filled?)
schema(:location) do |loc|
loc.key(:lat)
loc.key(:lng)
end
end
```
This is a trivial example just to show the syntax, the reason for using `schema` rather than just `key` is when you want to use higher-level concepts like `rule` interface. I'll add a feature where a schema class can be passed too, so that you can share schemas across other schemas (such schemas!) easily and avoid duplication.
Not sure if generic is a good name (feedback welcome!) but the idea is that after rules have been applied you can take …

Nested schemas and generic rules composition

---

config/errors.yml
spec/integration/error_compiler_spec.rb

```ruby
require 'bundler/setup'
require 'dry-validation'
UserSchema = Dry::Validation.Schema do
key(:sample) { empty? }
end
result = UserSchema.({
sample: [23]
})
unless result.success?
puts result.messages
end
```
That reads bad: "Sample cannot be empty", but it should be "Sample must be empty".

Fix empty predicate error message

---

config/errors.yml

`:odd?` and `:even?` predicates are included in dry-logic and should therefore be included in the default messages yaml.

Add odd? and even? message defaults

---

lib/dry/validation/input_processor_compiler.rb
spec/integration/schema/using_types_spec.rb

I was interested in looking at https://github.com/dry-rb/dry-validation/issues/103 - I've managed to get a passing spec (without breaking the build) but I can't help feeling that that this isn't the _actual_ solution. I'd love to seeing another failing spec.

Fix bug when validating custom types

---

dry-validation.gemspec

`dry-types` v0.7.1 introduced `JSON::*` coercions which dry-v relies on.

Update dry-types deps to support JSON coercions

---

Gemfile
config/errors.yml
lib/dry/validation/error_compiler/input.rb
spec/integration/error_compiler_spec.rb
spec/integration/schema/check_rules_spec.rb

Use `included_in?` instead of `inclusion?` and `excluded_from?` instead of `exclusion?`.
These predicates are deprecated by `dry-logic` See https://github.com/dry-rb/dry-logic/pull/9.

Use included_in? and excluded_from?

---

spec/integration/form/predicates/array_spec.rb

following dry-types PR 88, ‘’ coerces to [] which is an array.

fix form array specs

---

lib/dry/validation/input_processor_compiler/form.rb
spec/integration/form/predicates/false_spec.rb
spec/integration/form/predicates/true_spec.rb
spec/integration/schema/predicates/lt_spec.rb

Also add specs
fixes #157 
we no longer need an accepted macro instead you can just call `required(:terms).value(:true?)`

enable coercion on form.true and form.false

---

lib/dry/validation/error_compiler/input.rb
spec/fixtures/locales/en.yml
spec/integration/custom_error_messages_spec.rb

Currently there is no way to access all parameters of a custom predicate in the error message.
This pr just makes every parameter of a custom predicate method available (value is already available).
For now this means all args are accessible by `arg0`, `arg1` and so on.
Relates to #114

Custom predicate params in error messages

---

lib/dry/validation/schema/value.rb
spec/integration/schema/macros/each_spec.rb
spec/integration/schema/macros/when_spec.rb

This enables you to use predicates that require options (e.g. size, min_size etc.) with the each and when macros.
Specs have been enhanced to cover both cases and a fix applied to correctly handle the conversion of predicate hash to array.
Fixes #171

Fix bug when using predicates with options in each and when

---

spec/integration/schema/predicates/array_spec.rb

Added some failing spec for the case when `each` is used in a Schema with an `input_processor`.
Related to #170

`each` not applying `array?` before hand when used with an `input_processor`

---

lib/dry/validation/messages/abstract.rb
spec/integration/error_compiler_spec.rb

I've updated the `Validation::Messages::Abstract` class `lookup_path` to allow the ability to specify a custom error message for the `key?` predicate.
I've added the spec to `error_compiler_spec.rb` but am uncertain if that is the right spec that conveys the desired behavior.
This should address issue #116.
Any additional feedback is welcomed.

add ability to specify custom error message for 'key?'

---

lib/dry/validation.rb
lib/dry/validation/schema.rb
lib/dry/validation/schema/deprecated.rb
lib/dry/validation/schema/dsl.rb
lib/dry/validation/schema/form.rb
lib/dry/validation/schema/json.rb
lib/dry/validation/schema/rule.rb
lib/dry/validation/schema/value.rb
spec/integration/schema/form/explicit_types_spec.rb
spec/integration/schema/json/explicit_types_spec.rb
spec/integration/schema_spec.rb
spec/spec_helper.rb

This extends existing `required` and `optional` interfaces to support explicit type specs that are used for input coercion which is applied prior validation. This is a pretty big change as we're separating coercion from validation in the DSL too.
Here's how it works:
``` ruby
Dry::Validation.Form do
configure { config.type_specs = true }
required(:name, :string)
required(:age, [:nil, :int])
required(:address).schema do
required(:street, :string)
required(:city, :string)
required(:zipcode, :string)
end
required(:phone_numbers).each do
schema do
required(:prefix, :string)
required(:num, :string)
end
end
end
```
Notice that this is **a pure sanitization/coercion schema** without any rules.
Scope of this PR:
As a second step, which will be done in another PR, I'll add a way to infer rules …

Separate type specs / coercions from predicates

---

lib/dry/validation/error_compiler.rb
lib/dry/validation/error_compiler/input.rb
lib/dry/validation/hint_compiler.rb
lib/dry/validation/messages/abstract.rb
lib/dry/validation/result.rb
lib/dry/validation/schema.rb
spec/integration/form/predicates/size/range_spec.rb
spec/integration/hints_spec.rb
spec/integration/schema/predicates/size/range_spec.rb
spec/integration/schema/using_types_spec.rb

* Add support for `predicate.failure` and `predicate.hint` lookup path
* Select failure messages over hints even when their text is different
* Fix a horrible bug where Schema.rule_ast would duplicate rules 4
times resulting in hints being generated 4 times (lol!)
closes #184

Extend hint functionality and fix issues

---

lib/dry/validation/hint_compiler.rb

This commit improves performance for at least this benchmark:
```ruby
require 'benchmark/ips'
require 'dry-validation'
schema = Dry::Validation.Schema do
required(:address).schema do
required(:city).filled(min_size?: 3)
required(:street).filled
required(:country).schema do
required(:name).filled
required(:code).filled
end
end
end
INPUT = { address: { city: 'NYC' } }.freeze
errors = schema.call({}).messages
puts errors.inspect
Benchmark.ips do |x|
x.report do
schema.call(INPUT).messages
end
end
```
```
Warming up --------------------------------------
224.000  i/100ms
Calculating -------------------------------------
2.252k (± 1.2%) i/s -     11.424k in   5.072491s
```
```
Warming up --------------------------------------
257.000  i/100ms
Calculating ------------------------------------- …
```

Avoid HintCompiler allocations w/ empty options

---

lib/dry/validation/messages/abstract.rb

dbf9534 made benchmarks fast but tests slow so it has been
reverted in 944558f
This commit make benchmarks _and_ tests fast(er) again by
lazily caching the cache in a ivar.
/cc @solnic

Reduce method calls by caching as ivar lazily

---

CHANGELOG.md
lib/dry/validation/error_compiler.rb
spec/integration/schema/nested_schemas_spec.rb

The issue was with the error compiler mutating an array in `visit_schema` that continued to be passed around when further processing other parts of the errors, which resulted in error messages being incorrectly nested.
This resolves #221 (and perhaps some other issues too, since we a few different strangely structured error message hashes as a consequence of this bug).

Fix bug with messages hash not matching nested sibling schemas

---

lib/dry/validation/message_compiler.rb
lib/dry/validation/messages/abstract.rb
lib/dry/validation/messages/i18n.rb
lib/dry/validation/messages/yaml.rb
spec/fixtures/locales/pl.yml
spec/integration/messages/i18n_spec.rb
spec/unit/error_compiler_spec.rb

Based on the conversation in the Issue **#216** the situation was that the default_locale was fixed on `:en` and thus also when you were setting the `config.messages = :i18n` you were obliged to pass the `locale` as a parameter to the messages.
@solnic let me know if this is what you was expecting or you had a different idea?
Thanks! 👍

Use I18n.locale or I18n.default_locale when the config specify :18n for the messages

---

lib/dry/validation/input_processor_compiler/form.rb
lib/dry/validation/input_processor_compiler/json.rb
lib/dry/validation/input_processor_compiler/sanitizer.rb
lib/dry/validation/predicate_registry.rb
spec/unit/input_processor_compiler/form_spec.rb
spec/unit/input_processor_compiler/json_spec.rb

Ruby 2.4.0 unifies Fixnum and Bignum into Integer.
https://bugs.ruby-lang.org/issues/12005
Fix following deprecated warnings in Ruby 2.4.0-preview3.
`warning: constant ::Fixnum is deprecated`
Thanks.

Fix deprecated warnings in Ruby 2.4.0+

---

Rakefile

Hello, it seemed that there were two rspec/core imports in the project's Rakefile (per issue #292). I have removed the second one from inside the first task.

Removed duplicate 'rspec/core import in rake file

---

spec/integration/custom_predicates_spec.rb
spec/integration/form/predicates/empty_spec.rb
spec/integration/form/predicates/filled_spec.rb
spec/integration/form/predicates/max_size_spec.rb
spec/integration/form/predicates/min_size_spec.rb
spec/integration/form/predicates/none_spec.rb
spec/integration/form/predicates/size/fixed_spec.rb
spec/integration/form/predicates/size/range_spec.rb
spec/integration/schema/predicates/empty_spec.rb
spec/integration/schema/predicates/filled_spec.rb
spec/integration/schema/predicates/gt_spec.rb
spec/integration/schema/predicates/gteq_spec.rb
spec/integration/schema/predicates/key_spec.rb
spec/integration/schema/predicates/lt_spec.rb
spec/integration/schema/predicates/lteq_spec.rb
spec/integration/schema/predicates/max_size_spec.rb
spec/integration/schema/predicates/min_size_spec.rb
spec/integration/schema/predicates/none_spec.rb
spec/integration/schema/predicates/size/fixed_spec.rb
spec/integration/schema/predicates/size/range_spec.rb
spec/integration/schema/predicates/type_spec.rb

I found these while test-driving a `rubocop-rspec` cop that checks for redundant "it"s in test docstrings.
- Removes redundant 'it's at the beginning of test docstrings.
- Converts 'should raise error' and 'is raises error' to just
'raises error' which is consistent with the other examples in
the codebase.
I'm happy to make similar changes to other `dry-*` repos if that would be helpful/desired, just lmk!

Refactor test docstrings

---

lib/dry/validation/schema/class_interface.rb
spec/integration/injecting_rules_spec.rb

When injecting rules from to a new schema the original's rules are also modified

Bug when injecting rules into a schema

---

CONTRIBUTING.md
README.md

All of the links in CONTRIBUTE.md were broken. This fixes them (and dries the links for easier future fixing :) ) and adds a link from readme to contribution doc.

Fix links in the contribution document

---

lib/dry/validation/messages/abstract.rb

Just a fix for removing the warning when rejecting extra states on a Hash
https://github.com/ruby/ruby/blob/v2_4_1/hash.c#L1335-L1337
Thanks!

Fix `warning: extra states are no longer copied`

---

lib/dry/validation/message_compiler.rb
spec/spec_helper.rb

This is a workaround which suppresses warnings issued by Kernel.sprintf in
presence of extra keys when interpolating a template string. Now, dry-v won't
pollute other projects with a ton of useless warnings. I did some research
on the subject and found out that:
1. The current behavior of MRI is not going to change anytime soon
https://bugs.ruby-lang.org/issues/2709
https://bugs.ruby-lang.org/issues/5763
2. What i18n did about this
a) ignored warnings
b) implemented interpolation in pure Ruby
c) added efficient interpolation compiler (this is kinda unrelated but since
it improves the performance we can have it too to compensate the slowdown
caused by implementing "sprintf" in Ruby)
https://github.com/svenfuchs/i18n/issues/65
https://github.com/svenfuchs/i18n/blob/0a0fa8e5e7f4497e0c39c046b2 …

Suppress interpolation warnings

---

CHANGELOG.md
Gemfile
lib/dry/validation/extensions/monads.rb
spec/extensions/monads/result_spec.rb

Keeping it in sync with the latest changes in dry-monads, as in, `Either` became `Result`. Since having `Result#to_result` would be awkward I chose `#to_monad` instead.

Rename Result#to_either to #to_monad

---

lib/dry/validation/messages/i18n.rb
spec/fixtures/locales/pl.yml
spec/integration/messages/i18n_spec.rb

Currently, rules translations don't work when i18n is enabled.

Return correct rule name while using i18n

---

lib/dry/validation/schema/value.rb

The ruby interpreter warns when loading line 42. This reproduces with
```
% ruby -rdry-validation -wep
```
with current 0.12.2 gem.

⚠ method redefined; discarding old schema

---

lib/dry/validation/contract/class_interface.rb
spec/integration/contract/build_spec.rb

Added `.build` to `Dry::Validation::Contract`.
It is just a shortcut that can be used to define contracts that won't be reused or inherited.

Implemented .build shortcut

---

lib/dry/validation/contract.rb
lib/dry/validation/contract/class_interface.rb
lib/dry/validation/evaluator.rb
lib/dry/validation/rule.rb
spec/integration/contract/class_interface/rule_spec.rb
spec/integration/contract/inherited_spec.rb
spec/integration/evaluator_spec.rb

Adds support for the following syntax:
``` ruby
rule(:email, :login) do
failure("not valid") # defaults to using :email as the error identifier
end
rule(:email, :login) do
failure(:foo, "not valid") # sets :foo as the error identifier
end
```
When more than one key is provided, rule will be applied only if all values passed schema checks.

Expand rule API

---

Gemfile
Rakefile
lib/dry/validation.rb
lib/dry/validation/extensions/monads.rb
lib/dry/validation/result.rb
spec/extensions/monads/result_spec.rb
spec/spec_helper.rb

This is similar to monads in dry-validation 0.x but now failure/success
objects wrap entire result, not just data or errors.
/cc @timriley

Add :monads extension

---

lib/dry/validation/contract.rb
lib/dry/validation/error.rb
lib/dry/validation/error_set.rb
lib/dry/validation/evaluator.rb
lib/dry/validation/result.rb
spec/fixtures/messages/errors.en.yml
spec/integration/contract/class_interface/rule_spec.rb
spec/integration/contract/message_spec.rb

Refs #469 
Adds support for defining rules w/o any path, so that their failures won't be associated with any key path or identifier, making them "base" errors associated with the entire input.
Here's an example:
``` ruby
require 'dry/validation/contract'
require 'byebug'
class NewUserContract < Dry::Validation::Contract
params do
required(:email).filled(:string)
end
rule do
failure('Sorry, users can only sign up on weekends') unless weekend?
end
def weekend?
%w[Sat Sun].include?(Date.today.strftime('%a'))
end
end
contract = NewUserContract.new
puts contract.(email: '').errors.inspect
puts contract.(email: '').base_errors.inspect
```

Add support for base errors not associated with any key

---

lib/dry/validation/error.rb
lib/dry/validation/error_set.rb
lib/dry/validation/result.rb
spec/extensions/monads/result_spec.rb
spec/integration/contract/call_spec.rb
spec/integration/contract/class_interface/rule_spec.rb
spec/integration/contract/evaluator/setting_values_spec.rb
spec/integration/contract/external_deps_spec.rb
spec/integration/contract/using_messages_spec.rb
spec/integration/result_spec.rb

This is a significant change and improvement - `Result#errors` returns now an instance of `ErrorSet`, this object holds both message objects from dry-schema and validation error objects, too. It quacks like a hash, so `#[]` and `#each` + rest of enum works.
It **is a breaking change** because `#errors` is no longer a hash.
The main motivation behind this change is dealing with "base" errors because they have no keys associated with them. It was weird to deal with them separately from other errors as `Result#errors` didn't include them, which could be surprising or even lead to bugs.
Another reason is that it reduces `Result` API, which is always a good thing and it puts more emphasis on the richer `ErrorSet` object.

Error set as the errors

---

lib/dry/validation/contract.rb
lib/dry/validation/error.rb
lib/dry/validation/error_set.rb
lib/dry/validation/evaluator.rb
lib/dry/validation/messages.rb
lib/dry/validation/messages/i18n.rb
lib/dry/validation/messages/resolver.rb
lib/dry/validation/messages/yaml.rb
lib/dry/validation/result.rb
spec/fixtures/messages/errors.en.yml
spec/fixtures/messages/errors.pl.yml
spec/integration/contract/using_messages_spec.rb
spec/integration/evaluator_spec.rb
spec/integration/messages/resolver_spec.rb
spec/integration/result_spec.rb
spec/spec_helper.rb

This restores support for passing options to `Result#errors`:
``` ruby
require 'dry/validation/contract'
class NewUserContract < Dry::Validation::Contract
params do
required(:email).filled(:string)
end
end
contract = NewUserContract.new
puts contract.(email: '').errors.inspect
puts contract.(email: '').errors(locale: :pl).inspect
puts contract.(email: '').errors(full: true).map(&:to_s)
```
Closes #479 
Closes #480

Error options

---

lib/dry/validation/evaluator.rb
lib/dry/validation/result.rb
spec/integration/contract/using_messages_spec.rb

Having it defined in classes that are not completely Hash-like is a common source of problems due to implicit conversions made by ruby when passing keywords around. Current ruby behavior may change in the future but for now it seems it's better not to define `to_hash` without clear benefits.

Remove Result#to_hash

---

CHANGELOG.md
lib/dry/validation/contract.rb
lib/dry/validation/evaluator.rb
lib/dry/validation/result.rb
lib/dry/validation/rule.rb
spec/integration/contract/evaluator/using_context_spec.rb
spec/integration/evaluator_spec.rb
spec/integration/result_spec.rb

Add shared context to rules for additional storage

---

lib/dry/validation/error.rb
lib/dry/validation/messages/resolver.rb
spec/integration/contract/evaluator/failure_spec.rb
spec/integration/messages/resolver_spec.rb

This adds support for passing not just the text of a message, but also any arbitrary meta-data you may need.
Refs dry-rb/dry-schema#39

Allow passing text + meta to failure

---

lib/dry/validation/extensions/monads.rb
spec/extensions/monads/result_spec.rb

Result objects from dry-schema and dry-validation have rich API that we lose if we convert it to primitives. Simple wrapping with Success/Failure will work better. See https://github.com/dry-rb/dry-schema/pull/116

Wrap whole validation result with result monad

---

lib/dry/validation/contract.rb
lib/dry/validation/result.rb
spec/integration/contract/evaluator/using_context_spec.rb

@solnic I think we don't want to pass context around as an option so it's another argument for `Result.new`. I'm not sure if we want to simplify `Result#call` to take context from `result`

Add context to Result

---

config/errors.yml
lib/dry/validation.rb
lib/dry/validation/contract.rb
lib/dry/validation/contract/class_interface.rb
lib/dry/validation/evaluator.rb
lib/dry/validation/macros.rb
lib/dry/validation/rule.rb
spec/integration/macros/accepted_spec.rb

This adds a simple API for registering macros and the first macro called `:acceptance`.
``` ruby
Dry::Validation::Macros.register(:even_numbers) do
key.failure("all numbers must be even because reasons") unless values[key_name].all?(&:even?)
end
class MyContract < Dry::Validation::Contract
params do
required(:numbers).array(:integer)
end
rule(:numbers).validate(:even_numbers)
end
mc = MyContract.new
mc.(numbers: ['2'])
mc.(numbers: ['1'])
```
❗️ `Rule#validate` can accept one or more macro identifiers. ❗️ 
❗️ Macro functions are evaluated via `Evaluator`, so they act as normal rule validation blocks❗️ 
Closes #157

Add "acceptance" macro

---

lib/dry/validation/constants.rb
lib/dry/validation/contract.rb
lib/dry/validation/evaluator.rb
lib/dry/validation/failures.rb
lib/dry/validation/rule.rb
spec/integration/contract/call_spec.rb
spec/integration/contract/class_interface/rule/array_spec.rb
spec/integration/evaluator_spec.rb

This adds a convenient method for validating elements of an array. Just like with any other rule, the validation function is only applied when schema checks passed **for a given value**.
``` ruby
require 'dry/validation'
class Props < Dry::Validation::Contract
params do
required(:props).array(:string)
end  
rule(:props).each do
key.failure('bad format') unless /[a-z]+/.match?(value)
end  
end  
props_contract = Props.new
props_contract.(props: ['foo', 1, '1234', 'hello']).errors.to_h
```
As a bonus, I added `Evaluator#value` which returns the value under the first key, which is a nice general addition useful in all rule types.

Rules for arrays

---

lib/dry/validation/constants.rb
lib/dry/validation/evaluator.rb
lib/dry/validation/function.rb
lib/dry/validation/macro.rb
lib/dry/validation/rule.rb
spec/integration/contract/evaluator/using_context_spec.rb
spec/integration/macros/custom_macros_spec.rb

This makes rule block arguments more flexible, instead of using positioned arguments (which was `|context|` or `|context, macro|` for blocks used from macros) we have a "dynamic" kwarg approach. By defining kwargs in your blocks you specify what you need in your blocks.

Use kwargs in rule and macro functions

---

lib/dry/validation/values.rb
spec/unit/values_spec.rb

Fix values reader with hash paths

---

lib/dry/validation/evaluator.rb
lib/dry/validation/values.rb
spec/integration/contract/call_spec.rb
spec/unit/values_spec.rb

This is helpful when dealing with optional keys. We can't just assume
that we do not want to execute a rule when a value was missing.
Good example: a password must be provided when login is provided, and
both are optional.
Refs #540

Add key? method to rule blocks

---

dry-validation.gemspec
lib/dry/validation.rb
lib/dry/validation/extensions/predicates_as_macros.rb
spec/extensions/predicates_as_macros/contract_spec.rb

PoC for `:gteq?`
This is the implementation for #537 
Some considerations:
- Right now it just loads with `:gteq?` predicate. We have to decide which predicates need to be imported. My proposal is:
- empty?
- filled?
- odd?
- even?
- lt?
- gt?
- lteq?
- gteq?
- size?
- min_size?
- max_size?
- inclusion?
- exclusion?
- included_in?
- excluded_from?
- includes?
- excludes?
- eql?
- is?
- not_eql?
- true?
- false?
- uuid_v4?
- respond_to?
- I think `Dry::Validation::Predicate#arg_names` and `Dry::Validation::Predicate#call` should be moved to `Dry::Schema::PredicateRegistry`.
- I think it would be nice to keep `name` and `options` in the generated error when doing `.failure(name, options)`. If I'm understanding what it is happening, they are just used as an intermediate info to build the …

Extension to use dry-logic predicates as macros

---

lib/dry/validation/function.rb
lib/dry/validation/rule.rb
spec/integration/contract/class_interface/rule/each_spec.rb

This also fixes uncached calls to `block.parameters` after calling `with`

Pass keyword arguments to `each` rule

---

lib/dry/validation/contract/class_interface.rb
spec/integration/contract/class_interface/json_spec.rb
spec/integration/contract/class_interface/params_spec.rb
spec/integration/contract/class_interface/schema_spec.rb

Let `Dry::Validation::Contract.schema`, `.params`, and `.json` to return defined schema when invoked without block.
As per agreement with @solnic & @flash-gordon.
```ruby
class EmptyContract < Dry::Validation::Contract
end
EmptyContract.schema # => nil
```
```ruby
class AddressContract < Dry::Validation::Contract
schema do
required(:city).value(:string)
end
end
AddressContract.schema # => #<Dry::Schema::Processor keys=[:city] rules={:city=>"key?(:city) AND key[city](str?)"}>
```
```ruby
class TravelContract < Dry::Validation::Contract
params do
required(:destination).value(:string)
end
end
TravelContract.schema # => #<Dry::Schema::Params keys=["destination"] rules={:destination=>"key?(:destination) AND key[destination](str?)"}>
TravelContract.params # => #<Dry::Schema::Params …
```

Dry::Validation::Contract.schema to return defined schema

---

lib/dry/validation/contract.rb
lib/dry/validation/schema_ext.rb
spec/integration/contract/class_interface/rule/nested_data_spec.rb

Fix guarding rules with nested values specified as a hash

---

lib/dry/validation/contract/class_interface.rb
spec/integration/contract/class_interface/schema_spec.rb

This is a small tweak to the feature added in #580, based on the feature request in #574 
If you are defining a schema externally, it makes sense that you won't always need to extend the schema inside the contract. This PR allows the following:
```ruby
class MySchema < Dry::Schema::Params
end
class MyContract < Dry::Validation::Contract
params MySchema.new
end
```

Don't require block argument with external schema

---

lib/dry/validation/contract/class_interface.rb
spec/integration/contract/class_interface/schema_spec.rb
spec/integration/contract/using_messages_spec.rb

This allows dry-validation to make use of the multiple parent feature in dry-schema (https://github.com/dry-rb/dry-schema/pull/191)
This is a BC change, the schema/params/json methods now take one or more parent schemas as an argument

Multiple parent schemas

---

lib/dry/validation/message_set.rb
spec/integration/result_spec.rb

MessageSet in Dry::Validation allows for the set to be manipulated after init.  Its superclass attempts to cache the result of computing #empty? by setting the @empty ivar.
Because of this #empty? will always return true if it is called prior to #add_error.
This pull request fixes that bug by setting @empty to nil when #add_error is called.

Bug fix: MessageSet caches empty? too early

---

lib/dry/validation/contract/class_interface.rb
lib/dry/validation/schema_ext.rb

Using `flat_map` over `map.flatten` is 1.6 faster according to [Enumerable#map...Array#flatten vs Enumerable#flat_map](https://github.com/JuanitoFatas/fast-ruby#enumerablemaparrayflatten-vs-enumerableflat_map-code).
Failing specs are unrelated i.e. they also fail on `master` branch.

Replace map flatten with flat_map

---

lib/dry/validation/failures.rb
lib/dry/validation/messages/resolver.rb
spec/integration/contract/evaluator/failure_spec.rb

as discussed here: https://github.com/dry-rb/dry-validation/issues/584

Add an explicit error when failure is configured with an invalid hash

---

lib/dry/validation/message_set.rb
spec/integration/contract/class_interface/rule/nested_data_spec.rb

This PR solves the problem with a path intersection.
Currently, the longest path can be processed a first and made this a `Hash`, instead of `Array`. 
Solution: sort paths by size.
If you need a spec, please tell me where I should place it, because currently, I do not understand where I should place this case.
Example:
```rb
require 'dry/validation'
class MyForm < Dry::Validation::Contract
params do
required(:rules).each do
schema do
required(:domains).each(:str?)
end
end
end
rule(:rules).each do
key(path.keys + [:domains]).failure('Failed')
key.failure('Failed')
end
end
puts MyForm.new.call(rules: [{domains: ['some']}]).errors.to_h
```
Expected:
```rb
{:rules=>{0=>[["Failed"], {:domains=>["Failed"]}]}}
```
Got:
```
Traceback (most recent call last):
10: from dry-v.rb:18:in `<main>'
9: …
```

Fix error messages path sorting

---

lib/dry/validation/message_set.rb

This pull request makes `Dry::Validation::MessageSet#with` implementation a little bit more more efficient.
The idea behind the pull request is that for any two arrays `a` and `b`,  `a | b` is functionally equivalent to `(a + b).uniq`, but it is faster because it doesn't allocate an intermediate array. 
Artificial benchmarks:
```ruby
require 'benchmark/ips'
[
[:small,
[:a, :b],
[:b, :c, :b]
],
[:both_empty,
[],
[]
],
[:left_empty,
[],
[:b, :c, :c, :e]
],
[:right_empty,
[:b, :c, :d, :b],
[]
],
[:huge,
Array.new(1000) { rand(100) },
Array.new(1000) { rand(100) }
]
].each do |type, other, this|
fail 'boom' unless (other + this).uniq == other | this
puts "=== #{type} ==="
Benchmark.ips do |x|
x.report('+.uniq') { (other + this).uniq }
x.report('|') { other | this }
x.compare!
end
end
__END__ …
```

Optimize the performance of `MessageSet#with`

---

lib/dry/validation/extensions/predicates_as_macros.rb
spec/extensions/predicates_as_macros/contract_spec.rb

Add missing `format?` predicate as macro

---

lib/dry/validation/messages/resolver.rb
spec/fixtures/messages/errors.en.yml
spec/integration/contract/using_messages_spec.rb

Parse list tokens as comma separated list in msgs

---

.github/workflows/custom_ci.yml
Gemfile
docsite/source/index.html.md
docsite/source/pattern-matching.html.md
dry-validation.gemspec
lib/dry/validation/result.rb
spec/integration/result/pattern_matching_spec.rb
spec/spec_helper.rb

Two possible ways of matching a result:
1. With keys
```ruby
case contract_result
in foo:, bar: 'baz'
end
```
2. With arrays (tuple, pair of hash values)
```ruby
case contract_result
in { value_from_input: }, { context_value: }
end
```

Add support for pattern matching on result values

---

docsite/source/configuration.html.md

It has to be a String 'cause if not you'll have an error:
```ruby
TypeError:
no implicit conversion of Symbol into String
```

Change top_namespace type to String instead of Symbol

---

lib/dry/validation/rule.rb
spec/integration/macros/custom_macros_spec.rb

Fix macros expecting a range as option

---

docsite/source/rules.html.md
lib/dry/validation/evaluator.rb
lib/dry/validation/failures.rb
spec/integration/contract/evaluator/errors_spec.rb

This tries to implement what has been discussed in #615 
@flash-gordon @solnic please, take a look at the WIP code... the spec is failing because `#error?(:email)` returns false, even when it has an error added in the first rule. It's because `Evaluator#error?` delegates to `Result#error?`, which in turn delegates to `Dry::Schema::Result#error?`. Is it intended behaviour? I mean, we are looking just to the errors set in the schema phase and ignoring rules.

Add `Evaluator#schema_error?` and `Evaluator#rule_error?`

---

Gemfile
lib/dry/validation/messages/resolver.rb

After dry-rb/dry-schema#233 the `Messages::Abstract#[]` API changed and it now returns a hash with `text` and `meta` already populated, because text evaluation is now handled by the backend (which is a really good thing).
This PR simply updates internals to work with the changed `#[]` API.

Update Resolver to the new messages API

---

lib/dry/validation/message_set.rb

This code is no longer needed due to https://github.com/dry-rb/dry-schema/pull/248, but needs https://github.com/dry-rb/dry-schema/pull/250 to land before it passes CI.

Remove old MessageSet to_h code

---

Gemfile
lib/dry/validation/messages/resolver.rb

Reverts dry-rb/dry-validation#626.
Will fail until dry-schema's template API is restored.

Revert "Update Resolver to the new messages API"

---

lib/dry/validation/evaluator.rb
lib/dry/validation/macros.rb
lib/dry/validation/values.rb

-  an attempt to reduce warnings and still keep the documentation legible
Before this change, there were a few warnings when generating documentation.
> Building YARD (yri) index for dry-validation-1.5.0...
lib/dry/validation/macros.rb:28: [UnknownParam] @param tag has unknown parameter name: *args. Did you mean `args`?
lib/dry/validation/values.rb:38: [UnknownParam] @param tag has unknown parameter name: key
lib/dry/validation/evaluator.rb:149: [UnknownTag] Unknown tag @public
lib/dry/validation/evaluator.rb:172: [UnknownParam] @param tag has unknown parameter name: A
- Are there technical terms for the Schema::Path-compatible argument I tried to document, which was called "key"?

doc: YARD annotations with more documentation

---

lib/dry/validation/extensions/hints.rb

It is not needed here and leads to an error when not using dry-monads

Don't require dry-monads in hints extension.

---

docsite/source/schemas.html.md

This sentence doesn't make sense with this word included. Maybe it used to say 'the latter'' in a previous version of the text, but even then the sentence reads clearly without it.
The 'Edit on github' link and GH's in-browser editing makes these changes easy to propose :)

Typo: remove 'latter'

---

docsite/source/schemas.html.md

- With the JSON examples where an integer was passed in as an argument, the example output formatted these as strings incorrectly
- One example of the Params schema passed in a `"31"` string and the example output kept it as a string, but when running the code it is converted to an integer `31` which matches a previous explanation
- Fix multi-line formatting of one of the examples

Fix example output for returned data types

---

docsite/source/external-dependencies.html.md

* This change addresses https://github.com/dry-rb/dry-validation/issues/637 by adding a `dry-initializer` reference to the external dependencies page.

Mention dry-initializer on external dependencies page

---

docsite/source/schemas.html.md

This PR removes duplicated paragraph on JSON coercion from "Re-using schemas" section (the original paragraph is in "Defining a schema with JSON coercion" section)

Remove duplicated paragraph from schemas documentation

---

docsite/source/schemas.html.md

This text is a copy of the last bit under the JSON coercion section, and doesn't seem like it belongs under "Re-using schemas".

Remove duplicated paragraph

---

lib/dry/validation/values.rb
spec/unit/values_spec.rb

Fix key? predicate when path points to a non-existent array value

---

lib/dry/validation/contract.rb
lib/dry/validation/evaluator.rb
lib/dry/validation/result.rb
lib/dry/validation/rule.rb
spec/integration/result_spec.rb

Not super happy with this as of now :) Exchanged usage of
error? with schema_error? in the code base as otherwise there
thankfully were a bunch of failures.
The implementation of error? itself is basically stolen from
its counterpart at `Schema::Result`. It makes sense to check
if there are any errors for this but not sure if we shouldn't
rather still call out to schema_result.error?
Also, root/base behavior is a bit of a mystery.
Fix attempt for #655

Make Result#error?(key) return true for rule and schema errors

---

lib/dry/validation/messages/resolver.rb
spec/fixtures/messages/errors.en.yml
spec/fixtures/messages/errors.ja.yml
spec/fixtures/messages/errors.pl.yml
spec/integration/messages/resolver_spec.rb

Fix full error messages

---

lib/dry/validation/messages/resolver.rb
spec/fixtures/messages/errors.en.yml
spec/integration/contract/class_interface/rule/each_spec.rb

Resolves #663
This allows using custom errors by a key without an index when used in .each.
I guess there should be a better way to check if this is related to .each than by checking the keys array size, let me know if you have any ideas.

Support per-key custom errors for array paths

---

docsite/source/rules.html.md
lib/dry/validation/evaluator.rb
spec/integration/evaluator_spec.rb

When testing the presence of multiple, optional keys, it would be nice to be able to specify the key name to `key?` as you can with `values.key?`.
Since this merely delegates to that method, I can't see any reason why this omission was intentional. `#key_name` is preserved as the default argument, so this will not change any existing behavior.
[discussed in the forum here](https://discourse.dry-rb.org/t/better-consistency-for-key-method/1108/2)

Evaluator#key? forwards key name argument

---

dry-validation.gemspec

Last version `1.5.4` using the constant https://github.com/dry-rb/dry-validation/blob/master/lib/dry/validation/messages/resolver.rb#L9 from `dry-schema` which was introduced in version `1.5.2` https://github.com/dry-rb/dry-schema/blob/v1.5.2/lib/dry/schema/message_compiler.rb#L32
This patch fix `load_missing_constant` if project freeze gem versions and we update only dry-validation
Gemfile
```
gem "dry-schema", "1.5.0"
gem 'dry-validation', '1.5.4'
```
```
/usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:79:in `block in load_missing_constant': uninitialized constant Dry::Schema::MessageCompiler::FULL_MESSAGE_WHITESPACE (Name
Error)
from /usr/local/bundle/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in …
```

Set right dry-schema version

---

examples/basic.rb
examples/each.rb
examples/multiple.rb
examples/nested.rb

Some of the examples used outdated code, I think from before dry-schema was separated from dry-validation (?)

correct the code in some of the examples

---

lib/dry/validation/values.rb
spec/unit/values_spec.rb

Fix Undefined method `key?' for nil:NilClass error.

---

docsite/source/rules.html.md
lib/dry/validation/evaluator.rb
lib/dry/validation/result.rb
spec/integration/contract/evaluator/errors_spec.rb

Closing https://github.com/dry-rb/dry-validation/issues/658
Adds support for `#rule_error?` for checking that other rule has error
```ruby
class PersonContract < Dry::Validation::Contract
schema do
required(:email).filled(:string)
required(:name).filled(:string)
end
rule(:name) do
key.failure('name rule error')
end
rule(:email) do
key.failure('email rule error') if rule_error?(:name)
end
end
PersonContract.new.call(email: 'bar', name: 'foo').errors.to_h
```

adds support of explict argument for #rule_error? method

---

.gitignore
docsite/source/rules.html.md
lib/dry/validation/contract.rb
spec/integration/contract/evaluator/using_context_spec.rb

Implements https://github.com/dry-rb/dry-validation/issues/674

Add initial rules context interface

---

docsite/source/rules.html.md

Fixes a small typo in the rules section of the dry-validation documentation.

Fix a typo in the dry-validation rules page

---

project.yml

This ensures the dry-configurable 0.13.0 `setting` API is available (which we also use here)

Depend on dry-schema 1.8.0

---

docsite/source/messages.html.md

Fixing a small typo I noticed while reading the documentation - it mentions that there are 4 ways to set messages in the failure API, but 3 are listed.

Fix a typo in messages documentation page

---

lib/dry/validation/contract/class_interface.rb
spec/integration/contract/class_interface/rule_spec.rb

Fixes #705
I'm not completely sure of the fix, but it's probably good enough
as a starting point

Raise an InvalidKeyErrors on substring of valid keys

---

docsite/source/extensions.html.md

The extension got moved to dry-schema but it is still needed in
dry-validation to enable hints for contracts.

Add hints extension to docs

---

lib/dry/validation/contract.rb
spec/integration/contract/call_spec.rb

Given a `Contract` that has a duplicate key and some rule defined that passes through both of the keys:
```ruby
class DuplicatedKeyContract < Dry::Validation::Contract
schema do
required(:data).hash do
required(:wrapper).hash do
required(:data).hash.do
required(:id).filled(:string)
end
end 
end
end
register_macro(:min_size) do |macro:|
min = macro.args[0]
key.failure("must have at least #{min} characters") unless value.size >= min
end
rule(%i[data wrapper data id]).validate(min_size: 10)
end
DuplicateKeyContract.new.(data: { wrapper: { data: [] } } ) 
#=> TypeError: no implict conversion of Symbol to Integer
```
When the `rule`s where being evaluated we call `Contract#error?` in order to decide if we should skip testing the rule for that key. In the example above we would end up returning …

Duplicated keys mishandling in rule evaluation

---

lib/dry/validation/result.rb

Here:
https://github.com/dry-rb/dry-validation/blob/88a3c56898227f3c817d0e3e3acbe3aa8c61ae9f/dry-validation.gemspec#L28-L30
So the guard is not longer needed.

Removing guard since the gemspec requires RUBY_VERSION >= 2.7

---

lib/dry/validation/contract.rb
spec/integration/contract/call_spec.rb

As described in issue https://github.com/dry-rb/dry-validation/issues/716, the error raised when wrong input is given to the `Contract#call` method is confusing. It is the `NoMethodError` instead of `ArgumentError`.
I'm adding here a validation to fix that and return a descriptive error message.
If only we had a type system... ;)

Validate input type and return a descriptive error
