Gemfile, dry-validation.gemspec, lib/dry/validation.rb, lib/dry/validation/predicate_set.rb, lib/dry/validation/predicate_set/built_in.rb, lib/dry/validation/predicates.rb
Relies on https://github.com/dryrb/dry-container/pull/7 but could be done without if necessary
=> Add Dry::Validation::PredicateSet and BuiltIn

CHANGELOG.md
Just adding a thing I noticed to the CHANGELOG :)
=> Note rename of Schema::Result#params to #output

lib/dry/validation/hint_compiler.rb, lib/dry/validation/schema/rule.rb, lib/dry/validation/schema_compiler.rb, spec/integration/schema/using_types_spec.rb
Implements https://github.com/dry-rb/dry-validation/issues/83
This is pretty rough and introduces some duplication but I wanted to put it out there to get some feedback. Happy to make whatever changes are required.
=> Add support for enum dry types

lib/dry/validation/schema.rb, lib/dry/validation/schema/rule.rb, spec/integration/schema/using_types_spec.rb
Implements https://github.com/dry-rb/dry-validation/issues/85
Builds on https://github.com/dry-rb/dry-validation/pull/86 - I will rebase when merged.
=> Support inferring Dry::Type::Struct validations

Gemfile, examples/json.rb, lib/dry/validation.rb, lib/dry/validation/input_processor_compiler.rb, lib/dry/validation/input_processor_compiler/json.rb, lib/dry/validation/schema.rb, lib/dry/validation/schema/json.rb, spec/integration/schema/json_spec.rb, spec/unit/input_processor_compiler/json_spec.rb
Working on adding support for https://github.com/dry-rb/dry-types/issues/59.
=> Add JSON input processor

lib/dry/validation/schema.rb, spec/integration/schema_spec.rb
An attempt to resolve issue #136.
=> make .schema to accept objects that respond to #schema

Gemfile, config/errors.yml, lib/dry/validation.rb, lib/dry/validation/error_compiler/input.rb, lib/dry/validation/input_processor_compiler.rb, lib/dry/validation/predicate_registry.rb, lib/dry/validation/schema.rb, lib/dry/validation/schema/check.rb, lib/dry/validation/schema/dsl.rb, lib/dry/validation/schema/key.rb, lib/dry/validation/schema/rule.rb, lib/dry/validation/schema/value.rb, spec/fixtures/locales/pl.yml, spec/integration/custom_predicates_spec.rb, spec/integration/error_compiler_spec.rb, spec/integration/messages/i18n_spec.rb, spec/integration/schema/form_spec.rb, spec/integration/schema/json_spec.rb, spec/integration/schema/predicate_verification_spec.rb, spec/integration/schema/predicates/custom_spec.rb, spec/shared/predicate_helper.rb, spec/unit/hint_compiler_spec.rb, spec/unit/input_processor_compiler/form_spec.rb, spec/unit/input_processor_compiler/json_spec.rb, spec/unit/predicate_registry_spec.rb, spec/unit/schema/key_spec.rb, spec/unit/schema/rule_spec.rb, spec/unit/schema/value_spec.rb
=> [WIP] Use PredicateRegistry for setting up schemas

config/errors.yml, lib/dry/validation/message.rb, lib/dry/validation/message_compiler.rb, lib/dry/validation/schema/check.rb, lib/dry/validation/schema/dsl.rb, lib/dry/validation/schema/value.rb, spec/integration/hints_spec.rb, spec/integration/schema/check_rules_spec.rb, spec/integration/schema/using_types_spec.rb
=> Add support for "or" messages

CHANGELOG.md, Gemfile, Rakefile, lib/dry/validation/extensions.rb, lib/dry/validation/extensions/struct.rb, lib/dry/validation/schema/class_interface.rb, lib/dry/validation/schema/value.rb, spec/extensions/struct/schema_spec.rb, spec/integration/schema/using_types_spec.rb
This took me a dozen of minutes /cc @solnic @cored
=> Add dry-struct integration via an extension

lib/dry/validation/input_processor_compiler/form.rb, lib/dry/validation/input_processor_compiler/json.rb, lib/dry/validation/input_processor_compiler/sanitizer.rb
Fix https://github.com/dry-rb/dry-validation/pull/282/files#r90860843 .
=> Remove duplicated `Integer` key

lib/dry/validation/messages/namespaced.rb, spec/integration/localized_error_messages_spec.rb
=> Fixes issue with wrong localized error messages

examples/multiple.rb, lib/dry/validation/executor.rb, lib/dry/validation/schema.rb, lib/dry/validation/schema_compiler.rb, spec/integration/schema/validate_spec.rb
Fix this issue https://github.com/dry-rb/dry-validation/issues/299
Thanks @nicolas-besnard for the lovely spec. Hope that's fine when I use it in this PR.
=> Allow multiple validations on one field

Gemfile, dry-validation.gemspec, lib/dry/validation/input_processor_compiler.rb, lib/dry/validation/input_processor_compiler/form.rb, lib/dry/validation/input_processor_compiler/json.rb, lib/dry/validation/input_processor_compiler/sanitizer.rb
Update compiler to work with the latest version of `dry-types`
=> Update the compiler to work with latest version of dry-types

Gemfile, dry-validation.gemspec, lib/dry/validation/predicates.rb, lib/dry/validation/schema/class_interface.rb, spec/integration/messages/i18n_spec.rb
Upcoming dry-schema and dry-types release will depend on this version too, so we gotta bump it here as well so that people won't be blocked.
=> Bump dry logic

examples/json.rb, examples/params.rb, lib/dry/validation/contract/class_interface.rb
Added `json` blocks. Issue #446.
=> Add `json` blocks

lib/dry/validation/evaluator.rb, spec/integration/evaluator_spec.rb
=> Allow using `context` method in contracts/rule blocks

lib/dry/validation/result.rb, spec/integration/contract/evaluator/setting_values_spec.rb
=> Add Result#[]= and Result#key?

lib/dry/validation/constants.rb, lib/dry/validation/contract.rb, spec/fixtures/messages/errors.en.yml, spec/integration/contract/class_interface/rule_spec.rb, spec/integration/contract/message_spec.rb
=> Fix issues with message resolving

lib/dry/validation/contract.rb, lib/dry/validation/error.rb, lib/dry/validation/error_set.rb, lib/dry/validation/evaluator.rb, lib/dry/validation/result.rb, spec/integration/contract/class_interface/rule_spec.rb, spec/integration/contract/message_spec.rb, spec/integration/evaluator_spec.rb, spec/integration/result_spec.rb
=> Support for base errors with child errors

lib/dry/validation/error_set.rb
=> Memoize error set hash representation

lib/dry/validation/contract.rb, lib/dry/validation/evaluator.rb, lib/dry/validation/messages/resolver.rb, spec/integration/contract/call_spec.rb, spec/integration/contract/class_interface/rule_spec.rb, spec/integration/contract/evaluator/failure_spec.rb, spec/integration/contract/evaluator/setting_values_spec.rb, spec/integration/contract/external_deps_spec.rb, spec/integration/contract/using_messages_spec.rb, spec/integration/evaluator_spec.rb
=> Introduce key/base failure API

lib/dry/validation/contract.rb, lib/dry/validation/message.rb, lib/dry/validation/message_set.rb, lib/dry/validation/messages/resolver.rb, lib/dry/validation/result.rb, spec/integration/result_spec.rb
I made a mistake by calling these things errors/error_set because it's a
more generic concept. Using same names as in dry-schema is also better
for consistency.
=> Rename Error=>Message and ErrorSet=>MessageSet

lib/dry/validation.rb, lib/dry/validation/extensions/hints.rb, lib/dry/validation/message_set.rb, lib/dry/validation/result.rb, spec/extensions/hints/result_spec.rb, spec/integration/contract/evaluator/using_context_spec.rb
=> Add hints extension

lib/dry/validation/values.rb, spec/unit/values_spec.rb
=> Make Values#[] compatible with path specs

dry-validation.gemspec, lib/dry/validation/contract.rb, lib/dry/validation/contract/class_interface.rb, lib/dry/validation/schema_ext.rb, spec/integration/contract/class_interface/rule/nested_data_spec.rb, spec/integration/contract/class_interface/rule_spec.rb
=> Fix rule guarding for nested data

lib/dry/validation/contract.rb, spec/integration/contract/class_interface/rule/nested_data_spec.rb
=> Fix guarding array rules when keys are missing in the input

lib/dry/validation/result.rb, lib/dry/validation/rule.rb, spec/integration/contract/class_interface/rule/each_spec.rb
=> Improve guarding of each rules

lib/dry/validation/contract/class_interface.rb, spec/integration/contract/class_interface/rule_spec.rb
=> Skip checking rule keys when there is no schema

lib/dry/validation/values.rb, spec/unit/values_spec.rb
Trying to express better the intention, additionally it could be faster on cRuby and jRuby implementations
=> dry/validations/values/#[] - Use fetch_values on final map

lib/dry/validation/contract/class_interface.rb, spec/integration/contract/class_interface/schema_spec.rb
=> Add support for setting an external schema

docsite/source/configuration.html.md, docsite/source/extensions.html.md, docsite/source/external-dependencies.html.md, docsite/source/index.html.md, docsite/source/macros.html.md, docsite/source/messages.html.md, docsite/source/rules.html.md, docsite/source/schemas.html.md
Import documentation sources from dry-rb.org repository.
See dry-rb/dry-rb.org#357 for more info
=> Add docsite for 1.0

docsite/source/messages.html.md, docsite/source/rules.html.md, docsite/source/schemas.html.md
Also should be merged in master =)
=> [docsite] fix links

docsite/source/comparison-with-activemodel.html.md
Hi, just fix a link on the documentation!
=> Fix not found link on docs

spec/integration/contract/class_interface/rule/nested_data_spec.rb
A spec for issue described in https://github.com/dry-rb/dry-validation/issues/620#issue-553394163 The spec seems to now be passing so it seems like the issue has been fixed on master (that, or I'm doing something wrong).
=> Add spec for deeply nested array key setting

docsite/source/macros.html.md
=> [docsite] add info about macros and i18n

lib/dry/validation/message.rb, lib/dry/validation/message_set.rb, lib/dry/validation/messages/resolver.rb, spec/unit/rule_spec.rb
Bit ugly workaround but could not find better place to apply the full: true rule. 
Not really happy with it and looknig forward to change it if needed.
=> workaround for #618

lib/dry/validation/extensions/hints.rb, spec/extensions/hints/result_spec.rb
=> Fix:589 Transfer the options when invoking hints

docsite/source/rules.html.md, lib/dry/validation/rule.rb, spec/unit/rule_spec.rb
=> Expose index within each rules

lib/dry/validation/result.rb, spec/integration/contract/class_interface/rule/nested_data_spec.rb
=> Fix base error predicate

docsite/source/rules.html.md
Hey folks, just realized that I didn't update the docs after changes. And generally messed them up. Fixing it.
=> Fix initial context documentation

spec/integration/result/pattern_matching_spec.rb
replace single quotes to double quotes.
=> improve: pattern matching test
